"""member_onboarding_fields_change_requests_audit_logs

Revision ID: 139edfc2a0d1
Revises: 8c6de43cfbd6
Create Date: 2026-06-27 09:47:52.268569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139edfc2a0d1'
down_revision: Union[str, None] = '8c6de43cfbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
