"""family_change_request_columns

Revision ID: 487eda6900d7
Revises: 139edfc2a0d1
Create Date: 2026-06-27 11:24:59.484119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487eda6900d7'
down_revision: Union[str, None] = '139edfc2a0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_change_requests', sa.Column('entity_type', sa.String(), nullable=False, server_default='profile'))
    op.add_column('member_change_requests', sa.Column('entity_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_change_requests', 'entity_id')
    op.drop_column('member_change_requests', 'entity_type')
    # ### end Alembic commands ###
