"""add_mobile_no_to_users

Revision ID: 719290e18afe
Revises: 8443dc99561d
Create Date: 2026-06-15 20:17:21.313865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719290e18afe'
down_revision: Union[str, None] = '8443dc99561d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_no')
    # ### end Alembic commands ###
