"""member_onboarding_fields_change_requests_audit_logs

Revision ID: 8c6de43cfbd6
Revises: 2f9da2813e1e
Create Date: 2026-06-27 09:47:29.378354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c6de43cfbd6'
down_revision: Union[str, None] = '2f9da2813e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('llm_usage', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_usage', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_usage', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('llm_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_llm_usage_agent_name', table_name='llm_usage')
    op.drop_index('ix_llm_usage_created_at', table_name='llm_usage')
    op.add_column('member_profiles', sa.Column('sale_date', sa.Date(), nullable=True))
    op.add_column('member_profiles', sa.Column('sales_channel', sa.String(), nullable=True))
    op.add_column('member_profiles', sa.Column('branch_code', sa.String(), nullable=True))
    op.add_column('member_profiles', sa.Column('salesperson_name', sa.String(), nullable=True))
    op.add_column('member_profiles', sa.Column('employee_code', sa.String(), nullable=True))
    op.add_column('member_profiles', sa.Column('data1', sa.String(), nullable=True))
    op.add_column('member_profiles', sa.Column('data2', sa.String(), nullable=True))
    op.add_column('member_profiles', sa.Column('data3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_profiles', 'data3')
    op.drop_column('member_profiles', 'data2')
    op.drop_column('member_profiles', 'data1')
    op.drop_column('member_profiles', 'employee_code')
    op.drop_column('member_profiles', 'salesperson_name')
    op.drop_column('member_profiles', 'branch_code')
    op.drop_column('member_profiles', 'sales_channel')
    op.drop_column('member_profiles', 'sale_date')
    op.create_index('ix_llm_usage_created_at', 'llm_usage', ['created_at'], unique=False)
    op.create_index('ix_llm_usage_agent_name', 'llm_usage', ['agent_name'], unique=False)
    op.alter_column('llm_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('llm_usage', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('llm_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('llm_usage', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('llm_usage', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_table('member_change_requests')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
