"""partner_onboarding_fields

Revision ID: d31481f19fba
Revises: 487eda6900d7
Create Date: 2026-06-27 12:45:18.652822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31481f19fba'
down_revision: Union[str, None] = '487eda6900d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member_change_requests', 'entity_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('partners', sa.Column('state', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('legal_company_name', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('trade_name', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('registered_address', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('pin_code', sa.String(length=10), nullable=True))
    op.add_column('partners', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.add_column('partners', sa.Column('pan', sa.String(length=10), nullable=True))
    op.add_column('partners', sa.Column('authorized_signatory_name', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('data_1', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('data_2', sa.String(), nullable=True))
    op.add_column('partners', sa.Column('data_3', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'data_3')
    op.drop_column('partners', 'data_2')
    op.drop_column('partners', 'data_1')
    op.drop_column('partners', 'designation')
    op.drop_column('partners', 'authorized_signatory_name')
    op.drop_column('partners', 'pan')
    op.drop_column('partners', 'gstin')
    op.drop_column('partners', 'pin_code')
    op.drop_column('partners', 'registered_address')
    op.drop_column('partners', 'trade_name')
    op.drop_column('partners', 'legal_company_name')
    op.drop_column('partners', 'state')
    op.alter_column('member_change_requests', 'entity_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'profile'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
